[project]
name = "summate-ai"
version = "0.1.0"
description = "An rubric-based autograding framework for natural language student responses."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-ollama>=0.2.3",
    "ollama>=0.4.7",
]
